language: node_js
node_js:
  - "18"
env:
  - MONGODB_URI=mongodb+srv://user:pass@cluster.mongodb.net/online-shop
  - JWT_SECRET=your_secret_key
script:
  - cd backend && npm install && npm test
  - cd ../frontend && npm install && npm test
